apiVersion: apps/v1
kind: Deployment
metadata:
  name: emplyee-mgmt-frontend
  namespace: springbootapp-dev
  labels:
    app: emplyee-mgmt-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emplyee-mgmt-frontend
  template:
    metadata:
      labels:
        app: emplyee-mgmt-frontend 
    spec:
      containers:
      - name: emplyee-mgmt-frontend
        image: santoshk1296/emplyeemgmtfrontend:latest
        env:
          - name: EMPLOYEE_MGMT_API_SERVICE_HOST
            value: http://emplyee-mgmt-api
          - name: TZ
            value: Asia/Kolkata
        ports:
        - containerPort: 4200
            
---

apiVersion: v1
kind: Service
metadata:
  name: emplyee-mgmt-frontend
  namespace: springbootapp-dev
spec:
  selector:
    app: emplyee-mgmt-frontend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 4200
